# Generated by Django 6.0.6 on 2026-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='requires_booking',
            field=models.BooleanField(default=True, verbose_name='Richiede prenotazione'),
        ),
    ]
