# Generated by Django 6.0.6 on 2026-06-23 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Nome visualizzato')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergie')),
                ('food_preferences', models.TextField(blank=True, verbose_name='Preferenze alimentari')),
                ('has_car', models.BooleanField(default=False, verbose_name='Auto disponibile')),
                ('car_seats', models.PositiveIntegerField(default=0, verbose_name='Posti auto disponibili')),
                ('notes', models.TextField(blank=True, verbose_name='Note personali')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
