# Generated by Django 6.0.6 on 2026-06-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modello auto'),
        ),
    ]
