# Generated by Django 6.0.6 on 2026-06-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='car_model',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150, verbose_name='Luogo di nascita'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Numero documento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('CI', "Carta d'identità"), ('PATENTE', 'Patente')], max_length=20, verbose_name='Tipo di documento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='residence_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Luogo di residenza'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('M', 'Maschio'), ('F', 'Femmina'), ('ALTRO', 'Altro / preferisco non specificare')], max_length=20, verbose_name='Sesso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wants_linen_rental',
            field=models.BooleanField(default=False, verbose_name='Vuole noleggiare la biancheria'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome visualizzato'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='has_car',
            field=models.BooleanField(default=False, verbose_name='Ha auto disponibile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
