# Generated by Django 6.0.6 on 2026-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_car_model_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_issuing_authority',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ente rilascio documento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='residence_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Via / indirizzo di residenza'),
        ),
    ]
